/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc;

import Produto.Produto;
import Produto.ProdutoDAOJDBC;
import Vendedor.Vendedor;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Neto
 */
public class CadastrarProduto extends javax.swing.JDialog {
    private Vendedor vendedor_Local = null;
    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto(Vendedor vendedor) {
        initComponents();
        this.setModal(true);
        Vendedor vendedorL = new Vendedor(vendedor.getIdv(),vendedor.getNome(),vendedor.getLogin(),vendedor.getSenha());
        vendedor_Local = vendedorL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Produto = new javax.swing.JLabel();
        jTextField_InserirNomeProd = new javax.swing.JTextField();
        jLabel_NomeProd = new javax.swing.JLabel();
        jLabel_PrecoProd = new javax.swing.JLabel();
        jLabel_QuantProd = new javax.swing.JLabel();
        jTextField_InserirPrecoProd = new javax.swing.JTextField();
        jTextField_InserirQuantProd = new javax.swing.JTextField();
        jButton_Cadastrar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel_Creditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produto");
        setAlwaysOnTop(true);
        setFocusCycleRoot(false);
        setFocusTraversalPolicy(null);
        setFocusTraversalPolicyProvider(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jLabel_Produto.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel_Produto.setText("Produto");

        jTextField_InserirNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InserirNomeProdActionPerformed(evt);
            }
        });

        jLabel_NomeProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_NomeProd.setText("Nome:");

        jLabel_PrecoProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_PrecoProd.setText("Preço:");

        jLabel_QuantProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_QuantProd.setText("Estoque:");

        jTextField_InserirPrecoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InserirPrecoProdActionPerformed(evt);
            }
        });

        jTextField_InserirQuantProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InserirQuantProdActionPerformed(evt);
            }
        });

        jButton_Cadastrar.setText("Cadastrar");
        jButton_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel_Creditos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_Creditos.setText("Desenvolvido por M&N Software");
        jLabel_Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CreditosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Creditos))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(jButton_Cadastrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Cancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_NomeProd)
                                .addComponent(jLabel_PrecoProd)
                                .addComponent(jLabel_QuantProd))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_InserirNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_InserirPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_InserirQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel_Produto)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Produto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NomeProd)
                    .addComponent(jTextField_InserirNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_PrecoProd)
                    .addComponent(jTextField_InserirPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_QuantProd)
                    .addComponent(jTextField_InserirQuantProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cadastrar)
                    .addComponent(jButton_Cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel_Creditos))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-401)/2, (screenSize.height-318)/2, 401, 318);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_InserirNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InserirNomeProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InserirNomeProdActionPerformed

    private void jTextField_InserirPrecoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InserirPrecoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InserirPrecoProdActionPerformed

    private void jTextField_InserirQuantProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InserirQuantProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InserirQuantProdActionPerformed

    private void jButton_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarActionPerformed
        // TODO add your handling code here:
        ProdutoDAOJDBC produtodao = new ProdutoDAOJDBC();
        List<Produto> produtos;
        produtos= new ArrayList<>();
        try {
            produtos = produtodao.consultar();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton_CadastrarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jLabel_CreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CreditosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_CreditosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cadastrar;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JLabel jLabel_Creditos;
    private javax.swing.JLabel jLabel_NomeProd;
    private javax.swing.JLabel jLabel_PrecoProd;
    private javax.swing.JLabel jLabel_Produto;
    private javax.swing.JLabel jLabel_QuantProd;
    private javax.swing.JTextField jTextField_InserirNomeProd;
    private javax.swing.JTextField jTextField_InserirPrecoProd;
    private javax.swing.JTextField jTextField_InserirQuantProd;
    // End of variables declaration//GEN-END:variables
}
