/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc;

import Vendedor.Vendedor;
import Vendedor.VendedorDAOJDBC;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Neto
 */
public class CadastrarVendedor extends javax.swing.JDialog {
    private Vendedor vendedor_Local;
    /**
     * Creates new form CadastrarVendedor
     */
    public CadastrarVendedor(Vendedor vendedor) {
        initComponents();
        this.setModal(true);
        Vendedor vendedorL = new Vendedor(vendedor.getIdv(),vendedor.getNome(),vendedor.getLogin(),vendedor.getSenha());
        vendedor_Local = vendedorL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Creditos = new javax.swing.JLabel();
        jLabel_Vendedor = new javax.swing.JLabel();
        jLabel_VendProd = new javax.swing.JLabel();
        jTextField_InserirNomeVend = new javax.swing.JTextField();
        jLabel_LoginVend = new javax.swing.JLabel();
        jTextField_InserirLoginVend = new javax.swing.JTextField();
        jLabel_SenhaVend = new javax.swing.JLabel();
        jTextField_InserirSenhaVend = new javax.swing.JTextField();
        jLabel_ConfSenhaVend = new javax.swing.JLabel();
        jTextField_confSenhaVend = new javax.swing.JTextField();
        jButton_CadastrarVend = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Vendedor");
        setAlwaysOnTop(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jLabel_Creditos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_Creditos.setText("Desenvolvido por M&N Software");
        jLabel_Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CreditosMouseClicked(evt);
            }
        });

        jLabel_Vendedor.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel_Vendedor.setText("Vendedor");

        jLabel_VendProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_VendProd.setText("Nome:");

        jTextField_InserirNomeVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InserirNomeVendActionPerformed(evt);
            }
        });

        jLabel_LoginVend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_LoginVend.setText("Login:");

        jTextField_InserirLoginVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InserirLoginVendActionPerformed(evt);
            }
        });

        jLabel_SenhaVend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_SenhaVend.setText("Senha:");

        jTextField_InserirSenhaVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_InserirSenhaVendActionPerformed(evt);
            }
        });

        jLabel_ConfSenhaVend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_ConfSenhaVend.setText("Confirmar senha:");

        jTextField_confSenhaVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_confSenhaVendActionPerformed(evt);
            }
        });

        jButton_CadastrarVend.setText("Cadastrar");
        jButton_CadastrarVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarVendActionPerformed(evt);
            }
        });

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Creditos))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_VendProd)
                            .addComponent(jLabel_LoginVend)
                            .addComponent(jLabel_SenhaVend)
                            .addComponent(jLabel_ConfSenhaVend)
                            .addComponent(jButton_CadastrarVend))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_InserirLoginVend, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_InserirNomeVend, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_InserirSenhaVend, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_confSenhaVend, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton_Cancelar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel_Vendedor)))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Vendedor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_VendProd)
                    .addComponent(jTextField_InserirNomeVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LoginVend)
                    .addComponent(jTextField_InserirLoginVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SenhaVend)
                    .addComponent(jTextField_InserirSenhaVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ConfSenhaVend)
                    .addComponent(jTextField_confSenhaVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CadastrarVend)
                    .addComponent(jButton_Cancelar))
                .addGap(22, 22, 22)
                .addComponent(jLabel_Creditos))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-392)/2, (screenSize.height-347)/2, 392, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_InserirNomeVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InserirNomeVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InserirNomeVendActionPerformed

    private void jTextField_InserirLoginVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InserirLoginVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InserirLoginVendActionPerformed

    private void jTextField_InserirSenhaVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_InserirSenhaVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_InserirSenhaVendActionPerformed

    private void jTextField_confSenhaVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_confSenhaVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_confSenhaVendActionPerformed

    private void jLabel_CreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CreditosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_CreditosMouseClicked

    private void jButton_CadastrarVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarVendActionPerformed
        // TODO add your handling code here:
        boolean verifica = true;
        boolean mensagemnome = false;
        boolean mensagemlogin = false;
        VendedorDAOJDBC vendedordao = new VendedorDAOJDBC();
        List<Vendedor> vendedores;
        vendedores= new ArrayList<>();
        
        try {
            vendedores = vendedordao.consultar();
        } catch (Exception ex) {
            Logger.getLogger(CadastrarVendedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(Vendedor v: vendedores){
                if(vendedores.contains(jTextField_InserirNomeVend.getText()) && !"".equals(jTextField_InserirNomeVend.getText())){
                    if(vendedores.contains(jTextField_InserirLoginVend.getText()) && !"".equals(jTextField_InserirLoginVend.getText())){
                        if((jTextField_InserirSenhaVend.getText().equals(jTextField_confSenhaVend.getText())) && (!"".equals(jTextField_InserirSenhaVend.getText()))){
                            
                            verifica=false;
                            
                            Vendedor vendedorN = new Vendedor(jTextField_InserirSenhaVend.getText(),jTextField_InserirLoginVend.getText(),jTextField_InserirNomeVend.getText());      
                            
                            try {
                                vendedordao.criar(vendedorN);
                            } catch (Exception ex) {
                                Logger.getLogger(CadastrarVendedor.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
                            JOptionPane.showMessageDialog(rootPane, "Cadastro realizado com sucesso");
                            jTextField_InserirLoginVend.setText("");
                            jTextField_InserirNomeVend.setText("");
                            jTextField_InserirSenhaVend.setText("");
                            jTextField_confSenhaVend.setText("");
                        }
                    }else{
                        mensagemlogin = true;
                    }    
                }else{
                    mensagemnome = true;
                }                
            }
        
        if(verifica){
            if(mensagemnome){
                JOptionPane.showMessageDialog(rootPane,"Nome nulo ou já existente no banco de dados") ;
            }else{
                if(mensagemlogin){
                    JOptionPane.showMessageDialog(rootPane,"Login nulo ou já existente no banco de dados") ;
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Senhas distintas");
                    jTextField_InserirSenhaVend.setText("");
                    jTextField_confSenhaVend.setText("");
                    jTextField_InserirSenhaVend.requestFocus();
                }
            }
            
        }
    }//GEN-LAST:event_jButton_CadastrarVendActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarVendedor(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadastrarVend;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JLabel jLabel_ConfSenhaVend;
    private javax.swing.JLabel jLabel_Creditos;
    private javax.swing.JLabel jLabel_LoginVend;
    private javax.swing.JLabel jLabel_SenhaVend;
    private javax.swing.JLabel jLabel_VendProd;
    private javax.swing.JLabel jLabel_Vendedor;
    private javax.swing.JTextField jTextField_InserirLoginVend;
    private javax.swing.JTextField jTextField_InserirNomeVend;
    private javax.swing.JTextField jTextField_InserirSenhaVend;
    private javax.swing.JTextField jTextField_confSenhaVend;
    // End of variables declaration//GEN-END:variables
}
