/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc;

import Produto.Produto;
import Produto.ProdutoDAOJDBC;
import Produto.ProdutoTable;
import Vendedor.Vendedor;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Neto
 */
public class CadastrarVenda extends javax.swing.JDialog {
    private Vendedor vendedor_Local = null;
    /**
     * Creates new form CadastrarVenda
     */
    public CadastrarVenda( Vendedor vendedor) {
        initComponents();
        this.setModal(true);
        Vendedor vendedorL = new Vendedor(vendedor.getIdv(),vendedor.getNome(),vendedor.getLogin(),vendedor.getSenha());
        vendedor_Local = vendedorL;
        
        ProdutoDAOJDBC produtosdao = new ProdutoDAOJDBC();
        List<Produto> produtos;
        produtos = new ArrayList<>();

        try {
            produtos = produtosdao.consultar();
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaProdutos(produtos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_Vendas = new javax.swing.JScrollPane();
        jTable_Vendas = new javax.swing.JTable();
        jLabel_CadasVend = new javax.swing.JLabel();
        jTextField_Quantidade = new javax.swing.JTextField();
        jLabel_QuantProd = new javax.swing.JLabel();
        jButton_Confirmar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel_Creditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jTable_Vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane_Vendas.setViewportView(jTable_Vendas);

        jLabel_CadasVend.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel_CadasVend.setText("Cadastrar vendas");

        jLabel_QuantProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_QuantProd.setText("Quantidade:");

        jButton_Confirmar.setText("Confirmar compra");

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel_Creditos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_Creditos.setText("Desenvolvido por M&N Software");
        jLabel_Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CreditosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_Vendas)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel_QuantProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Confirmar)
                .addGap(46, 46, 46)
                .addComponent(jButton_Cancelar)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel_CadasVend)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Creditos))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel_CadasVend)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_Vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_QuantProd)
                    .addComponent(jTextField_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Confirmar)
                    .addComponent(jButton_Cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel_Creditos))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-664)/2, (screenSize.height-422)/2, 664, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jLabel_CreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CreditosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_CreditosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarVenda(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Confirmar;
    private javax.swing.JLabel jLabel_CadasVend;
    private javax.swing.JLabel jLabel_Creditos;
    private javax.swing.JLabel jLabel_QuantProd;
    private javax.swing.JScrollPane jScrollPane_Vendas;
    private javax.swing.JTable jTable_Vendas;
    private javax.swing.JTextField jTextField_Quantidade;
    // End of variables declaration//GEN-END:variables

public void consultarDadosTabelaProdutos(List<Produto> produtos) {
       ProdutoTable Tabela_Produtos = new ProdutoTable(produtos);
        jTable_Vendas.setModel(Tabela_Produtos);
        ajustarTamanhoColunasProduto();
    }

    private void ajustarTamanhoColunasProduto() {
        jTable_Vendas.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable_Vendas.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
}
