/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc;

import Produto.Produto;
import Produto.ProdutoDAOJDBC;
import Produto.ProdutoTable;
import Vendas.Venda;
import Vendas.VendaDAOJDBC;
import Vendas.VendaTable;
import Vendedor.Vendedor;
import Vendedor.VendedorDAOJDBC;
import Vendedor.VendedorTable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.management.counter.Units;

/**
 *
 * @author Neto
 */
public class JanelaADM extends javax.swing.JFrame {    
    private Vendedor vendedor_Local = null;
    /**
     * Creates new form JanelaADM
     */
    
    public JanelaADM(Vendedor vendedor) {
        initComponents();    
            jLabel_OlaVendedor.setText(jLabel_OlaVendedor.getText()+ vendedor.getNome());
            Vendedor vendedorL = new Vendedor(vendedor.getIdv(),vendedor.getNome(),vendedor.getLogin(),vendedor.getSenha());
            vendedor_Local = vendedorL;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_ADM = new javax.swing.JScrollPane();
        jTable_ADM = new javax.swing.JTable();
        jButton_CadasProduto = new javax.swing.JButton();
        jLabel_OlaVendedor = new javax.swing.JLabel();
        jButton_Logoff = new javax.swing.JButton();
        jPanel_Vendas = new javax.swing.JPanel();
        jLabel_VendasText = new javax.swing.JLabel();
        jButton_Venda = new javax.swing.JButton();
        jPanel_Vendedor = new javax.swing.JPanel();
        jButton_Vendedor = new javax.swing.JButton();
        jLabel_Vendedor = new javax.swing.JLabel();
        jPanel_Estoque = new javax.swing.JPanel();
        jButton_Estoque = new javax.swing.JButton();
        jLabel_EstText = new javax.swing.JLabel();
        jLabel_Creditos = new javax.swing.JLabel();
        jButton_CadasVendedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador do sistema");
        setBackground(new java.awt.Color(255, 204, 255));
        setLocationByPlatform(true);
        setResizable(false);

        jTable_ADM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane_ADM.setViewportView(jTable_ADM);

        jButton_CadasProduto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton_CadasProduto.setText("Cadastrar Produto");
        jButton_CadasProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadasProdutoActionPerformed(evt);
            }
        });

        jLabel_OlaVendedor.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel_OlaVendedor.setText("Olá ");

        jButton_Logoff.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton_Logoff.setText("Logoff");
        jButton_Logoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoffActionPerformed(evt);
            }
        });

        jLabel_VendasText.setText("Vendas");
        jLabel_VendasText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_VendasTextMouseClicked(evt);
            }
        });

        jButton_Venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vendas.jpg"))); // NOI18N
        jButton_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_VendasLayout = new javax.swing.GroupLayout(jPanel_Vendas);
        jPanel_Vendas.setLayout(jPanel_VendasLayout);
        jPanel_VendasLayout.setHorizontalGroup(
            jPanel_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VendasLayout.createSequentialGroup()
                .addComponent(jButton_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_VendasText)
                .addGap(30, 30, 30))
        );
        jPanel_VendasLayout.setVerticalGroup(
            jPanel_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VendasLayout.createSequentialGroup()
                .addComponent(jButton_Venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel_VendasText))
        );

        jButton_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vendedor.jpg"))); // NOI18N
        jButton_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VendedorActionPerformed(evt);
            }
        });

        jLabel_Vendedor.setText("Vendedor");
        jLabel_Vendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_VendedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_VendedorLayout = new javax.swing.GroupLayout(jPanel_Vendedor);
        jPanel_Vendedor.setLayout(jPanel_VendedorLayout);
        jPanel_VendedorLayout.setHorizontalGroup(
            jPanel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VendedorLayout.createSequentialGroup()
                .addComponent(jButton_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_VendedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_Vendedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_VendedorLayout.setVerticalGroup(
            jPanel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VendedorLayout.createSequentialGroup()
                .addComponent(jButton_Vendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel_Vendedor))
        );

        jButton_Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque.jpg"))); // NOI18N
        jButton_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EstoqueActionPerformed(evt);
            }
        });

        jLabel_EstText.setText("Estoque");
        jLabel_EstText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EstTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_EstoqueLayout = new javax.swing.GroupLayout(jPanel_Estoque);
        jPanel_Estoque.setLayout(jPanel_EstoqueLayout);
        jPanel_EstoqueLayout.setHorizontalGroup(
            jPanel_EstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EstoqueLayout.createSequentialGroup()
                .addComponent(jButton_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_EstoqueLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_EstText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_EstoqueLayout.setVerticalGroup(
            jPanel_EstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_EstoqueLayout.createSequentialGroup()
                .addComponent(jButton_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel_EstText))
        );

        jLabel_Creditos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_Creditos.setText("Desenvolvido por M&N Software");

        jButton_CadasVendedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton_CadasVendedor.setText("Cadastrar Vendedor");
        jButton_CadasVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadasVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_OlaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton_CadasProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_CadasVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Logoff)
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jPanel_Vendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jPanel_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Creditos))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_ADM)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CadasProduto)
                    .addComponent(jLabel_OlaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Logoff)
                    .addComponent(jButton_CadasVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_ADM, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Vendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Vendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(jLabel_Creditos))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-677)/2, (screenSize.height-427)/2, 677, 427);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CadasProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadasProdutoActionPerformed
        // TODO add your handling code here:
        CadastrarProduto cadastro = new CadastrarProduto(vendedor_Local);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton_CadasProdutoActionPerformed

    private void jButton_LogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoffActionPerformed
        // TODO add your handling code here:
        Janela_Principal jPrincipal = new Janela_Principal();
        jPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_LogoffActionPerformed

    private void jButton_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VendaActionPerformed
        // TODO add your handling code here:
        VendaDAOJDBC vendasdao = new VendaDAOJDBC();
        List<Venda> vendas;
        vendas = new ArrayList<>();

        try {
            vendas = vendasdao.consultarPorVendedor(vendedor_Local);
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaVendas(vendas);
    }//GEN-LAST:event_jButton_VendaActionPerformed

    private void jLabel_VendasTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_VendasTextMouseClicked
        // TODO add your handling code here:
        VendaDAOJDBC vendasdao = new VendaDAOJDBC();
        List<Venda> vendas;
        vendas = new ArrayList<>();

        try {
            vendas = vendasdao.consultarPorVendedor(vendedor_Local);
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaVendas(vendas);
    }//GEN-LAST:event_jLabel_VendasTextMouseClicked

    private void jLabel_EstTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EstTextMouseClicked
        // TODO add your handling code here:
        ProdutoDAOJDBC produtosdao = new ProdutoDAOJDBC();
        List<Produto> produtos;
        produtos = new ArrayList<>();

        try {
            produtos = produtosdao.consultarPorQuantidade();
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaProdutos(produtos);
    }//GEN-LAST:event_jLabel_EstTextMouseClicked

    private void jButton_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VendedorActionPerformed
        // TODO add your handling code here:
        VendedorDAOJDBC vendedordao = new VendedorDAOJDBC();
        List<Vendedor> vendedores;
        vendedores = new ArrayList<>();

        try {
            vendedores = vendedordao.consultar();
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaVendedor(vendedores);
    }//GEN-LAST:event_jButton_VendedorActionPerformed

    private void jButton_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EstoqueActionPerformed
        // TODO add your handling code here:
        ProdutoDAOJDBC produtosdao = new ProdutoDAOJDBC();
        List<Produto> produtos;
        produtos = new ArrayList<>();

        try {
            produtos = produtosdao.consultarPorQuantidade();
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaProdutos(produtos);
    }//GEN-LAST:event_jButton_EstoqueActionPerformed

    private void jLabel_VendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_VendedorMouseClicked
        // TODO add your handling code here:
        VendedorDAOJDBC vendedordao = new VendedorDAOJDBC();
        List<Vendedor> vendedores;
        vendedores = new ArrayList<>();

        try {
            vendedores = vendedordao.consultar();
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaVendedor(vendedores);
    }//GEN-LAST:event_jLabel_VendedorMouseClicked

    private void jButton_CadasVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadasVendedorActionPerformed
        // TODO add your handling code here:
        CadastrarVendedor cadastro = new CadastrarVendedor(vendedor_Local);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton_CadasVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaADM(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CadasProduto;
    private javax.swing.JButton jButton_CadasVendedor;
    private javax.swing.JButton jButton_Estoque;
    private javax.swing.JButton jButton_Logoff;
    private javax.swing.JButton jButton_Venda;
    private javax.swing.JButton jButton_Vendedor;
    private javax.swing.JLabel jLabel_Creditos;
    private javax.swing.JLabel jLabel_EstText;
    private javax.swing.JLabel jLabel_OlaVendedor;
    private javax.swing.JLabel jLabel_VendasText;
    private javax.swing.JLabel jLabel_Vendedor;
    private javax.swing.JPanel jPanel_Estoque;
    private javax.swing.JPanel jPanel_Vendas;
    private javax.swing.JPanel jPanel_Vendedor;
    private javax.swing.JScrollPane jScrollPane_ADM;
    private javax.swing.JTable jTable_ADM;
    // End of variables declaration
//GEN-END:variables
    public void consultarDadosTabelaVendas(List<Venda> vendas){    
        VendaTable Tabela_Vendas = new VendaTable(vendas);
        jTable_ADM.setModel(Tabela_Vendas);
        ajustarTamanhoColunasVendas();
    }
    private void ajustarTamanhoColunasVendas() {
        jTable_ADM.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable_ADM.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable_ADM.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTable_ADM.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable_ADM.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    public void consultarDadosTabelaProdutos(List<Produto> produtos) {
       ProdutoTable Tabela_Produtos = new ProdutoTable(produtos);
        jTable_ADM.setModel(Tabela_Produtos);
        ajustarTamanhoColunasProduto();
    }

    private void ajustarTamanhoColunasProduto() {
        jTable_ADM.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable_ADM.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable_ADM.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
    public void consultarDadosTabelaVendedor(List<Vendedor> vendedores) {
        VendedorTable Tabela_Vendedor = new VendedorTable(vendedores);
        jTable_ADM.setModel(Tabela_Vendedor);
        ajustarTamanhoColunasVendedor();
    }
    
    private void ajustarTamanhoColunasVendedor() {
        jTable_ADM.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable_ADM.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable_ADM.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
}
