/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc;

import Produto.Produto;
import Produto.ProdutoDAOJDBC;
import Produto.ProdutoTable;
import Vendas.Venda;
import Vendas.VendaDAOJDBC;
import Vendas.VendaTable;
import Vendedor.Vendedor;
import Vendedor.VendedorDAOJDBC;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Neto
 */
public class JanelaVendedor extends javax.swing.JFrame {
    private Vendedor vendedor_Local = null;
    /**
     * Creates new form JanelaVendedor
     */
    public JanelaVendedor(Vendedor vendedor) {
        initComponents();
        jLabel_OlaVendedor.setText(jLabel_OlaVendedor.getText()+ vendedor.getNome());
            Vendedor vendedorL = new Vendedor(vendedor.getIdv(),vendedor.getNome(),vendedor.getLogin(),vendedor.getSenha());
            vendedor_Local = vendedorL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_OlaVendedor = new javax.swing.JLabel();
        jButton_Logoff = new javax.swing.JButton();
        jLabel_Creditos = new javax.swing.JLabel();
        jScrollPane_Vendedor = new javax.swing.JScrollPane();
        jTable_Vendedor = new javax.swing.JTable();
        jPanel_Vendas = new javax.swing.JPanel();
        jLabel_VendasText = new javax.swing.JLabel();
        jButton_Venda = new javax.swing.JButton();
        jPanel_Estoque3 = new javax.swing.JPanel();
        jButton_Estoque3 = new javax.swing.JButton();
        jLabel_EstText3 = new javax.swing.JLabel();
        jPanel_Vendas5 = new javax.swing.JPanel();
        jLabel_RealComp = new javax.swing.JLabel();
        jButton_RealComp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendedor");
        setResizable(false);

        jLabel_OlaVendedor.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel_OlaVendedor.setText("Olá ");

        jButton_Logoff.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton_Logoff.setText("Logoff");
        jButton_Logoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoffActionPerformed(evt);
            }
        });

        jLabel_Creditos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_Creditos.setText("Desenvolvido por M&N Software");

        jTable_Vendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane_Vendedor.setViewportView(jTable_Vendedor);

        jLabel_VendasText.setText("Vendas");
        jLabel_VendasText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_VendasTextMouseClicked(evt);
            }
        });

        jButton_Venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vendas.jpg"))); // NOI18N
        jButton_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_VendasLayout = new javax.swing.GroupLayout(jPanel_Vendas);
        jPanel_Vendas.setLayout(jPanel_VendasLayout);
        jPanel_VendasLayout.setHorizontalGroup(
            jPanel_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VendasLayout.createSequentialGroup()
                .addComponent(jButton_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_VendasText)
                .addGap(27, 27, 27))
        );
        jPanel_VendasLayout.setVerticalGroup(
            jPanel_VendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_VendasLayout.createSequentialGroup()
                .addComponent(jButton_Venda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel_VendasText))
        );

        jButton_Estoque3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque.jpg"))); // NOI18N
        jButton_Estoque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Estoque3ActionPerformed(evt);
            }
        });

        jLabel_EstText3.setText("Estoque");
        jLabel_EstText3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EstText3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Estoque3Layout = new javax.swing.GroupLayout(jPanel_Estoque3);
        jPanel_Estoque3.setLayout(jPanel_Estoque3Layout);
        jPanel_Estoque3Layout.setHorizontalGroup(
            jPanel_Estoque3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Estoque3Layout.createSequentialGroup()
                .addComponent(jButton_Estoque3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_Estoque3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_EstText3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Estoque3Layout.setVerticalGroup(
            jPanel_Estoque3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Estoque3Layout.createSequentialGroup()
                .addComponent(jButton_Estoque3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel_EstText3))
        );

        jLabel_RealComp.setText("Realizar venda");
        jLabel_RealComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RealCompMouseClicked(evt);
            }
        });

        jButton_RealComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/compras.jpg"))); // NOI18N
        jButton_RealComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RealCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Vendas5Layout = new javax.swing.GroupLayout(jPanel_Vendas5);
        jPanel_Vendas5.setLayout(jPanel_Vendas5Layout);
        jPanel_Vendas5Layout.setHorizontalGroup(
            jPanel_Vendas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Vendas5Layout.createSequentialGroup()
                .addComponent(jButton_RealComp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Vendas5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_RealComp)
                .addGap(27, 27, 27))
        );
        jPanel_Vendas5Layout.setVerticalGroup(
            jPanel_Vendas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Vendas5Layout.createSequentialGroup()
                .addComponent(jButton_RealComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel_RealComp))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel_Vendas5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jPanel_Vendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Estoque3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Creditos))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_OlaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Logoff))
                    .addComponent(jScrollPane_Vendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel_Estoque3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_OlaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Logoff))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane_Vendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel_Vendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_Vendas5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(jLabel_Creditos))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-677)/2, (screenSize.height-427)/2, 677, 427);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoffActionPerformed
        // TODO add your handling code here:
        Janela_Principal jPrincipal = new Janela_Principal();
        jPrincipal.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_LogoffActionPerformed

    private void jLabel_VendasTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_VendasTextMouseClicked
        // TODO add your handling code here:
        VendaDAOJDBC vendasdao = new VendaDAOJDBC();
        List<Venda> vendas;
        vendas = new ArrayList<>();

        try {
            vendas = vendasdao.consultarPorVendedor(vendedor_Local);
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaVendas(vendas);
    }//GEN-LAST:event_jLabel_VendasTextMouseClicked

    private void jButton_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VendaActionPerformed
        // TODO add your handling code here:
        VendaDAOJDBC vendasdao = new VendaDAOJDBC();
        List<Venda> vendas;
        vendas = new ArrayList<>();

        try {
            vendas = vendasdao.consultarPorVendedor(vendedor_Local);
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaVendas(vendas);
    }//GEN-LAST:event_jButton_VendaActionPerformed

    private void jButton_Estoque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Estoque3ActionPerformed
        // TODO add your handling code here:
        ProdutoDAOJDBC produtosdao = new ProdutoDAOJDBC();
        List<Produto> produtos;
        produtos = new ArrayList<>();

        try {
            produtos = produtosdao.consultarPorQuantidade();
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaProdutos(produtos);
    }//GEN-LAST:event_jButton_Estoque3ActionPerformed

    private void jLabel_EstText3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EstText3MouseClicked
        // TODO add your handling code here:
        ProdutoDAOJDBC produtosdao = new ProdutoDAOJDBC();
        List<Produto> produtos;
        produtos = new ArrayList<>();

        try {
            produtos = produtosdao.consultarPorQuantidade();
        } catch (Exception ex) {
            Logger.getLogger(JanelaADM.class.getName()).log(Level.SEVERE, null, ex);
        }

        consultarDadosTabelaProdutos(produtos);
    }//GEN-LAST:event_jLabel_EstText3MouseClicked

    private void jLabel_RealCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RealCompMouseClicked
        // TODO add your handling code here:
        CadastrarVenda  cadastro = new CadastrarVenda(vendedor_Local);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jLabel_RealCompMouseClicked

    private void jButton_RealCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RealCompActionPerformed
        // TODO add your handling code here:
        CadastrarVenda  cadastro = new CadastrarVenda(vendedor_Local);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton_RealCompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaVendedor(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Estoque;
    private javax.swing.JButton jButton_Estoque1;
    private javax.swing.JButton jButton_Estoque2;
    private javax.swing.JButton jButton_Estoque3;
    private javax.swing.JButton jButton_Logoff;
    private javax.swing.JButton jButton_RealComp;
    private javax.swing.JButton jButton_Venda;
    private javax.swing.JButton jButton_Venda2;
    private javax.swing.JButton jButton_Venda3;
    private javax.swing.JButton jButton_Venda4;
    private javax.swing.JLabel jLabel_Creditos;
    private javax.swing.JLabel jLabel_EstText;
    private javax.swing.JLabel jLabel_EstText1;
    private javax.swing.JLabel jLabel_EstText2;
    private javax.swing.JLabel jLabel_EstText3;
    private javax.swing.JLabel jLabel_OlaVendedor;
    private javax.swing.JLabel jLabel_RealComp;
    private javax.swing.JLabel jLabel_VendasText;
    private javax.swing.JLabel jLabel_VendasText2;
    private javax.swing.JLabel jLabel_VendasText3;
    private javax.swing.JLabel jLabel_VendasText4;
    private javax.swing.JPanel jPanel_Estoque;
    private javax.swing.JPanel jPanel_Estoque1;
    private javax.swing.JPanel jPanel_Estoque2;
    private javax.swing.JPanel jPanel_Estoque3;
    private javax.swing.JPanel jPanel_Vendas;
    private javax.swing.JPanel jPanel_Vendas1;
    private javax.swing.JPanel jPanel_Vendas2;
    private javax.swing.JPanel jPanel_Vendas3;
    private javax.swing.JPanel jPanel_Vendas5;
    private javax.swing.JScrollPane jScrollPane_Vendedor;
    private javax.swing.JTable jTable_Vendedor;
    // End of variables declaration//GEN-END:variables

public void consultarDadosTabelaVendas(List<Venda> vendas){    
        VendaTable Tabela_Vendas = new VendaTable(vendas);
        jTable_Vendedor.setModel(Tabela_Vendas);
        ajustarTamanhoColunasVendas();
    }
    private void ajustarTamanhoColunasVendas() {
        jTable_Vendedor.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable_Vendedor.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable_Vendedor.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTable_Vendedor.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable_Vendedor.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    public void consultarDadosTabelaProdutos(List<Produto> produtos) {
       ProdutoTable Tabela_Produtos = new ProdutoTable(produtos);
        jTable_Vendedor.setModel(Tabela_Produtos);
        ajustarTamanhoColunasProduto();
    }

    private void ajustarTamanhoColunasProduto() {
        jTable_Vendedor.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable_Vendedor.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable_Vendedor.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
    
}
